spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backend
    username: root
    password: admin
  application:
    name: backend

  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create
    show-sql: true