spring:
  datasource:
    url: ${URL_DB}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  application:
    name: backend

  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create
    show-sql: true